apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80         # Port accessible inside the cluster
    nodePort: 32080    # External port exposed on the node
    targetPort: 8080   # Port that the service will forward traffic to inside the container
  selector:
    app: node-app
