apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres (base64 encoded)
  POSTGRES_PASSWORD: c2VjdXJlcGFzcw==  # securepass (base64 encoded)
